[server]
headless = true

[theme]
primaryColor = "#0282c6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f7fa"
textColor = "#1a1a2e"
font = "sans serif"

[browser]
gatherUsageStats = false
